import Layout from '@/components/layout/Layout';
import './globals.css';

export const metadata = {
  title: 'رستوران‌های زنجیره‌ای ترخینه',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
        <body className='text-estedad'>
          <Layout>
          <div className='min-h-screen'>{children}</div>
          </Layout>
        </body>
    </html>
  )
}
