import './globals.css'
import localFont from 'next/font/local';


const myFont = localFont({ src:[
  {
    path: '../../public/fonts/Estedad-Regular.woff2',
    weight: '400',
    style: 'normal',
  },
  {
    path: '../../public/fonts/Estedad-Bold.woff2',
    weight: '700',
    style: 'normal',
  },
] })

export const metadata = {
  title: 'رستوران های زنجیره ای ترخینه',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>{children}</body>
    </html>
  )
}
